theme: jekyll-theme-cayman
exclude:
  [
    vendor,
    include,
    node_modules,
    package.json,
    package-lock.json,
    iml-online-help.spec,
    Makefile,
    LICENSE,
    Gemfile,
    Gemfile.lock,
    travis_env,
  ]
version: "6.0.0.0"
package_name: "iml-6.0.0.0"
lustre_version: "2.12.2"
lustre_package_name: "lustre-2.12.2"
lustre_kernel_version: "3.10.0-957.10.1.el7"
e2fsprogs_version: "1.44.5"
centos_version: "7.6"
repository: "whamcloud/Online-Help"
