theme: jekyll-theme-cayman
exclude:
  [
    vendor,
    include,
    node_modules,
    package.json,
    package-lock.json,
    iml-online-help.spec,
    Makefile,
    LICENSE,
    Gemfile,
    Gemfile.lock,
    travis_env,
  ]
version: "6.1.0.0"
semver_version: "6.1.0"
package_name: "iml-6.1.0.0"
lustre_version: "2.12.4"
lustre_package_name: "lustre-2.12.4"
lustre_kernel_version: "3.10.0-1062.9.1.el7"
e2fsprogs_version: "1.45.2.wc1-0"
centos_version: "7.7"
repository: "whamcloud/Online-Help"
